Add faq section, change register section id
hacktoberfestnh/hacktoberfestnh.github.io pull request #12
Opened 2019-09-30 21:13 UTC by istumpf

## Add FAQ section
![FAQ](https://user-images.githubusercontent.com/8162419/65917523-e60d7600-e3ad-11e9-8890-59e4ba63a53d.gif)

Close #7

2019-09-30 21:15 UTC, boniattirodrigo approved these changes

2019-09-30 21:18 UTC, paulodiovani commented
- Se participar eu ganho camisetas?
  As camisetas são prêmios da Digital Ocean para quem abrir 4 pull requests durante o período da Hacktoberfest - de 1º a 31 de Outubro. Veja mais detalhes em https://hacktoberfest.digitalocean.com.

2019-09-30 21:21 UTC, boniattirodrigo commented
* Preciso levar computador?

2019-09-30 21:26 UTC, boniattirodrigo commented
* Esse evento fornece certificado?
  O evento não fornecerá certificado e também não será possível utilizá-lo como horas complementares para estudantes da Feevale.

2019-09-30 21:48 UTC, paulodiovani reviewed
please, hold.

2019-09-30 21:48 UTC, paulodiovani commented on index.html
> +                      O evento não fornecerá certificado e também não será possível utilizá-lo como horas complementares para estudantes da Feevale.
Let's check with Feevale if is possible to prove event attendance anyhow to use as complimentary hours.

For now, let's hold this PR.

2019-10-03 13:26 UTC, paulodiovani commented
Please add a couple _how it works_ question before the others:
Here's an example.

pt_BR:

- Como funciona a Hacktoberfest?
  A Hacktoberfest é um evento online para incentivar a colaboração em projetos open source que premia participantes que abrirem pelo menos 4 pull requests no período do evento. Após se inscrever no site oficial [hacktoberfest.digitalocean.com](https://hacktoberfest.digitalocean.com), quaisquer _pull requests_ abertos em projetos open-source estão valendo para concorrer a camiseta, fornecida pela DigitalOcean e Dev.

- Como funciona a Hacktoberfest NH?
  Em Novo Hamburgo - RS acontece um evento local ligado à Hacktoberfest com palestras e um _hackathon_. O propósito do evento é incentivar a comunidade local a participar da Hacktoberfest e ajudar quem tem menos experiência ou costume de utilizar git e github.


Another question could mention about swags, gifts and prizes for participantes.

pt_BR:

- O que eu ganho ao participar?
  Participantes que abrirem pelo menos 4 pull requests durante o período do evento ganham uma camiseta da Digital Ocean e Dev. Além dessa, várias outras empresas premiam colaborações específicas, como pode ser visto em [hacktoberfestswaglist.com](https://hacktoberfestswaglist.com/). Como extra, quem comparecer ao evento em Novo Hamburgo - RS estará concorrendo ao sorteio de vários brindes ao final da tarde de sábado.

2019-10-03 13:30 UTC, paulodiovani requested changes

2019-10-03 13:30 UTC, paulodiovani commented on index.html
> +                      Qualquer pessoa que tenha interesse em colaborar com projetos de código aberto, independente da área de atuação ou nível de conhecimento técnico.
Let's make the answers be understandable by themselves (without the questions):

> Qualquer pessoa que tenha interesse em colaborar com projetos de código aberto, independente da área de atuação ou nível de conhecimento técnico pode participar.

2019-10-03 13:30 UTC, paulodiovani commented on index.html
> +                      Não. Há diversas formas de contribuir, inclusive com design, documentação e traduções.
> Não é necessário saber programar. Há diversas formas de contribuir, inclusive com design, documentação e traduções.

2019-10-03 13:30 UTC, paulodiovani commented on index.html
> +                      As camisetas são prêmios da Digital Ocean e Dev para os primeiros 50.000 a abrir 4 pull requests durante o período da Hacktoberfest - de 1º a 31 de Outubro. Veja mais detalhes e
Please, break lines at 80th column, more or less, to make it more readable in the code.

2019-10-03 13:30 UTC, paulodiovani commented on index.html
> +                      As camisetas são prêmios da Digital Ocean e Dev para os primeiros 50.000 a abrir 4 pull requests durante o período da Hacktoberfest - de 1º a 31 de Outubro. Veja mais detalhes e
Also, check my previous comment with qa suggestions about _what do I earn?_. I think that can come just before this one.

2019-10-04 13:12 UTC, istumpf commented on index.html
> +                       <a target="_blank" href="https://hacktoberfest.digitalocean.com"><i class="fa fa-external-link" aria-hidden="true"></i> hacktoberfest.digitalocean.com</a>,
```suggestion
                       <a target="_blank" href="https://hacktoberfest.digitalocean.com">
                         <i class="fa fa-external-link" aria-hidden="true"></i> hacktoberfest.digitalocean.com
                       </a>,
```

2019-10-04 13:52 UTC, paulodiovani requested changes

2019-10-04 13:52 UTC, paulodiovani commented on index.html
> +                       utilizar git e github.
Em Novo Hamburgo - RS acontece um evento com palestras
                       e um <i>hackathon</i> com o propósito de incentivar a comunidade local a
                       participar da Hacktoberfest e ajudar quem tem menos experiência ou
                       pouca familiaridade com utilizar git e github.

2019-10-04 13:52 UTC, paulodiovani commented on index.html
> +                       quaisquer pull requests abertos em projetos open-source estão valendo para concorrer a camiseta,
```suggestion
                       quaisquer pull requests abertos em projetos de código aberto estão valendo para concorrer a camiseta,
```

2019-10-04 13:52 UTC, paulodiovani commented on index.html
> +                       ganham uma camiseta da Digital Ocean e Dev. Além dessa, várias outras empresas
```suggestion
                       ganham uma camiseta da Digital Ocean e Dev. Além disso, várias outras empresas
```

2019-10-04 13:52 UTC, paulodiovani commented on index.html
> +                       independente da área de atuação ou nível de conhecimento técnico pode participar.
```suggestion
                       independente da área de atuação ou nível de conhecimento técnico, pode participar.
```

2019-10-04 13:52 UTC, paulodiovani commented on index.html
> +                  <a data-toggle="collapse" href="#faq6" class="collapsed">Se participar eu ganho camisetas? <i class="fa fa-minus-circle plus"></i></a>
This questions should be just after  _O que eu ganho ao participar?_

It is a good idea to review and better organize the questions by topic.

2019-10-04 16:48 UTC, paulodiovani approved these changes

2019-10-04 16:48 UTC, merged